---

- name: ensure config directory
  file:
    path: "{{ flanneld_config_dir }}"
    state: directory

- name: install flanneld
  yum:
    name: "flannel-{{ flanneld_version }}"
    state: present
  notify: restart flanneld

- name: copy flanneld config
  template:
    src: flanneld.j2
    dest: "{{ flanneld_config_dir }}/flanneld"
  notify: restart flanneld
